[package]
name = "os_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
panic = "abort" # 禁用 panic 时栈展开, 这样就不用提供 en_personality 语言项

[profile.release]
panic = "abort" # 禁用 panic 时栈展开